import Head from 'next/head';
import { Fragment } from 'react';
import { dehydrate, QueryClient } from '@tanstack/react-query';
import { useAuth, withAuth } from 'auth';
import { getAuth } from 'api/auth';
import { AUTH } from 'constants/queryKeys';

export default function Home() {
   const { authUser } = useAuth();

   return (
      <Fragment>
         <Head>
            <title>Create Next App</title>
            <meta content='Generated by create next app' name='description' />
            <meta
               content='width=device-width, initial-scale=1'
               name='viewport'
            />
            <link href='/favicon.ico' rel='icon' />
         </Head>

         <main className='m-10 text-5xl font-semibold text-blue-500'>
            Hello {authUser?.name}
         </main>
      </Fragment>
   );
}

export const getServerSideProps = withAuth(async () => {
   const queryClient = new QueryClient();

   await queryClient.prefetchQuery({
      queryFn: getAuth,
      queryKey: [AUTH],
   });

   return {
      props: {
         dehydratedState: dehydrate(queryClient),
      },
   };
});
